# SPDX-FileCopyrightText: 2026 UnionTech Software Technology Co., Ltd.
# SPDX-License-Identifier: GPL-3.0-or-later

name: 'SPDX Header Checker'
description: 'Validate SPDX copyright headers on pull requests'
author: 'UnionTech Software Technology Co., Ltd.'

branding:
  icon: 'check-circle'
  color: 'blue'

inputs:
  base:
    description: 'Base reference to diff against (e.g., origin/main)'
    required: false
    default: 'origin/main'
  include:
    description: 'Comma-separated list of glob patterns to include'
    required: false
    default: ''
  exclude:
    description: 'Comma-separated list of glob patterns to exclude'
    required: false
    default: ''
  year:
    description: 'Current year for validation (default: current UTC year)'
    required: false
    default: ''
  debug:
    description: 'Enable debug mode with detailed output for each file'
    required: false
    default: 'false'
  all-files:
    description: 'Check all files in repository instead of only changed files'
    required: false
    default: 'false'

runs:
  using: 'composite'
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Run SPDX header validation
      shell: bash
      run: |
        base_ref="${{ inputs.base }}"
        include_patterns="${{ inputs.include }}"
        exclude_patterns="${{ inputs.exclude }}"
        year="${{ inputs.year }}"
        debug="${{ inputs.debug }}"
        all_files="${{ inputs.all-files }}"

        args="--base $base_ref"

        if [ -n "$include_patterns" ]; then
          args="$args --include $(echo $include_patterns | tr ',' ' ')"
        fi

        if [ -n "$exclude_patterns" ]; then
          args="$args --exclude $(echo $exclude_patterns | tr ',' ' ')"
        fi

        if [ -n "$year" ]; then
          args="$args --year $year"
        fi

        if [ "$debug" = "true" ]; then
          args="$args --debug"
        fi

        if [ "$all_files" = "true" ]; then
          args="$args --all-files"
        fi

        python3 "${{ github.action_path }}/scripts/check_spdx_headers.py" $args
